### ISSUE TITLE
the 2 level module names like @google-cloud/bigquery not working?

### ISSUE THREAD

**Issue by c0b** [broofa/npmgraph#1]
just read from node-weekly, tried this one but not working?
http://npm.broofa.com/?q=@google-cloud/bigquery

it's valid one
https://www.npmjs.com/package/@google-cloud/bigquery

**Comment by broofa** [comment]
Ah, right. I'm parsing the query param as "module_name/module_version" (i.e. same format as npm repository API uses), so that's probably part of the problem. There may also be a URL escaping issue.  It looks like the app is trying to fetch stats from https://registry.npmjs.cf//google-cloud/bigquery instead of https://registry.npmjs.cf/@google-cloud%2fbigquery.

I'll figure this out and push and update by this evening (I hope).

**Comment by broofa** [comment]
Should be working now.  Thanks!
