### ISSUE TITLE
Can't drop package.json on the online version

### ISSUE THREAD

**Issue by Mic75** [broofa/npmgraph#2]
First of all, thanks a lot for this awesome tool!

I just encountered a small issue while playing with the online version, dropping a package.json file does not seem to work, I get the following dialog popping:
![2018-01-08_14-33-45](https://user-images.githubusercontent.com/1568791/34688748-2745bb00-f481-11e7-9416-dbe85a95cece.png)

Tested on chrome 63 and windows 10

**Comment by broofa** [comment]
Huh.   This is working for me, Chrome 63 on MacOS.  

I'll ask the obvious question of, "Are you sure the file you're dropping has a `.json` extension?"

Assuming that's not the issue and it's a Windows-specific issue, it would be helpful if you could debug this.  (Git pull, open 'index.html' file in your browser, no server needed.)  Try commenting out https://github.com/broofa/npmgraph/blob/master/index.js#L541 to see if file dropping works otherwise, etc.

**Comment by Mic75** [comment]
Yep, I do confirm the file as the .json extension.
Firefox (57) does not have the issue.

Also, commenting the line you pointed out make it work.

Debugging on chrome shows that `item.type` is empty, sounds like a chrome issue to me.

**Comment by broofa** [comment]
I disabled the check when `item` is undefined.  Please confirm that this fixes the issue.

**Comment by Mic75** [comment]
Working like a charm!
