### ISSUE TITLE
Uploading packages leads to `(Uploaded package)` appearing in the URL and search field

### ISSUE THREAD

**Issue by fregante** [broofa/npmgraph#36]
<img width="679" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/103596350-5bc29480-4ec3-11eb-803a-5c1a4f8c08b1.png">

0. Any browser
1. Upload package.json
2. Notice the URL bar and the search field
3. Refresh page and see nonsensical content

This is not a big bug, it's just a little annoyance because I have to empty the search field before searching again

**Comment by broofa** [comment]
Yup, bug... and also expected behavior at this point in time.  😄 

Currently uploaded packages are just parsed / stored in memory and disappear on page refresh, so reconstituting the graph isn't possible.  Possible solutions:

* Be more explicit about the above.  (e.g. Display "Please re-upload file to see graph" or something)
* Store uploaded package contents in LocalStorage

Th latter  is somewhat problematic...

* Allow more than one package to persist in memory?  (E.g. Can we support the case where local-project A depends on local-project B, allowing user to upload both packages?)
* Detecting when a previously uploaded package is re-uploaded (probably not a big deal, actually)
* Security concerns with retaining package.json contents indefinitely?  How / if / when should projects be removed from localStorage?

**Comment by fregante** [comment]
If you want to store it temporarily just to enable refreshes you can use history.replaceState or sessionStorage, but the actual issue is that the URL still is pointless. I suppose that you could store the dependency list in the URL itself and solve both problems, but I think there’s a URL length limit.

**Comment by broofa** [comment]
Hadn't considered SessionStorage but, yeah, that would solve the security and retention issues.

`replaceState` probably makes the most sense.  This is actually exactly the sort of thing it's designed for I think.

**Comment by broofa** [comment]
Actually, history state gets dropped on the floor when a page refreshes so doesn't help this situation.  (Which is interesting... really diminishes the value of history state ☹️ ).  Looks like it's gonna have to be localStorage.

**Comment by fregante** [comment]
Honestly I’d just look into fixing the URL and search field. Retaining the package across reloads doesn’t sound worth it.

**Comment by fregante** [comment]
🎉

**Comment by broofa** [comment]
Uploaded files are now stored in sessionStorage.  There's also a recent files list: 
![image](https://user-images.githubusercontent.com/164050/103700545-7ba49780-4f59-11eb-9e90-3a4a7c891bae.png)

And if I've done this properly, this allows for the local-project-A depends on local-project-B case (as long as the package names and versions are declared and consistent across the uploaded files.)
