### ISSUE TITLE
Always assumes oldest-possible package; should assume latest-possible?

### ISSUE THREAD

**Issue by dtgriscom** [broofa/npmgraph#7]
Given each dependency specification, it looks like the code fetches the oldest possible version of each package. For example, http-auth@3.2.3 specifies apache-md5 ^1.0.6. Since the latest version of apache-md5 is 1.1.2, that's the version that npm would fetch. However, the generated graph shows apache-md5@1.0.6.

I'll suggest that the graph should use the version that npm would fetch (I don't even know if there's a way to tell npm "fetch the oldest possible version of each dependency").

**Comment by danmarshall** [comment]
@broofa - thanks for this awesome project! I find it super handy. 🥇 

I'm also experiencing this issue. To fix it however, I suppose it would increase the download size, because you'd also have to download the manifest for each package.

Looking at the network traffic in my debugger, it appears that npmgraph relies on a package mirror on https://npmjs.cf/ . My guess is that this mirror is static, and there isn't a way to query it dynamically. Ideally you'd like to query by semver, like `^1`.

Take d3-format as an example. Querying for a specific [version 1.3.2](https://registry.npmjs.cf/d3-format/1.3.2) the download size is 1.9kb. A query for [the entire history](https://registry.npmjs.cf/d3-format/) is 65kb.

Not sure if people want the tradeoff?

**Comment by broofa** [comment]
I'm not sure about the limitations of npmjs.cf .vs. npmjs.org.  The reason I use npmjs.cf is that it supports CORS (and HTTP2), so requests can be made directly from the browser rather than having to go through a proxy of some sort.

I'm happy to take a PR if someone wants to look into this.  I don't have time at the moment, however.

**Comment by broofa** [comment]
Fixed in a40a3c0b52a265b53c0651f594060bef995e1547
